version: "3.3"

services:

    app:
        build:
            context: .
            dockerfile: ./Dockerfile
        container_name: auth_service_app
#        depends_on:
#            - db
        volumes:
            - "./:/app"
            - "../common_service:/common_service"
        ports:
            - "8001:8001"
        restart: always

#    db:
#        image: postgres:latest
#        container_name: auth_service_db
#        ports:
#            - "5432:5432"


